### ISSUE TITLE
Error when trying to run easyvpn

### ISSUE THREAD

**Issue by tzekid** [rodrigogs/easyvpn#2]
When I tried to run the example code I got:
```javascript
λ easyvpn -c US     
info: disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
info: Options error: You must define TUN/TAP device (--dev)
info: Use --help for more information.
info:  
info: child process exited with code 1
```

... after that I tried to read the `--help` section and got:

```javascript
λ easyvpn --help
error:  TypeError: May not write null values to stream
    at validChunk (_stream_writable.js:209:10)
    at WriteStream.Writable.write (_stream_writable.js:243:12)
    at resolve (/usr/lib/node_modules/easyvpn/index.js:26:48)
    at Promise._execute (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/promise.js:77:14)
    at vpns.slice.map (/usr/lib/node_modules/easyvpn/index.js:26:18)
    at Array.map (native)
    at WriteStream.writer.on (/usr/lib/node_modules/easyvpn/index.js:25:41)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:1942:10)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

--> [`at resolve (/usr/lib/node_modules/easyvpn/index.js:26:48)`](https://git.io/vDeZo)

**Comment by rodrigogs** [comment]
The error you have is caused because you dont have any `TUN/TAP` adapter installed. On Windows, Openvpn needs a `TUN/TAP` adapter to work.

https://community.openvpn.net/openvpn/wiki/BridgingAndRouting

Regarding the `--help` option... I'm working on it :)

**Comment by rodrigogs** [comment]
![asdasd](https://cloud.githubusercontent.com/assets/2362425/22348966/caa5ebf6-e3f4-11e6-9cf9-5932c31e9860.png)

Just to make things more clear.

**Comment by arjunmayilvaganan** [comment]
```
 ~ easyvpn -c IN                         
info: Querying data...
error: uncaughtException: Response code 403 (Forbidden) date=Fri Jan 27 2017 09:45:43 GMT+0530 (IST), pid=67973, uid=501, gid=20, cwd=/Users/arjunmayilvaganan, execPath=/usr/local/Cellar/node/7.4.0/bin/node, version=v7.4.0, argv=[/usr/local/Cellar/node/7.4.0/bin/node, /usr/local/bin/easyvpn, -c, IN], rss=32464896, heapTotal=18853888, heapUsed=10630312, external=152169, loadavg=[1.10107421875, 1.060546875, 1.103515625], uptime=1020963, trace=[column=24, file=/usr/local/lib/node_modules/easyvpn/node_modules/got/index.js, function=EventEmitter.ee.on.res, line=182, method=ee.on.res, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=EventEmitter.emit, line=188, method=emit, native=false, column=8, file=/usr/local/lib/node_modules/easyvpn/node_modules/got/index.js, function=Immediate.setImmediate, line=61, method=setImmediate, native=false, column=20, file=timers.js, function=runCallback, line=651, method=null, native=false, column=5, file=timers.js, function=tryOnImmediate, line=624, method=null, native=false, column=5, file=timers.js, function=processImmediate [as _immediateCallback], line=596, method=null, native=false], stack=[HTTPError,     at EventEmitter.ee.on.res (/usr/local/lib/node_modules/easyvpn/node_modules/got/index.js:182:24),     at emitOne (events.js:96:13),     at EventEmitter.emit (events.js:188:7),     at Immediate.setImmediate (/usr/local/lib/node_modules/easyvpn/node_modules/got/index.js:61:8),     at runCallback (timers.js:651:20),     at tryOnImmediate (timers.js:624:5),     at processImmediate [as _immediateCallback] (timers.js:596:5)]
info: Starting openvpn...
info: Fri Jan 27 09:45:43 2017 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode
info: Options error: You must define TUN/TAP device (--dev)
info: Use --help for more information.
info:  
info: child process exited with code 1
```

Hello,
I have `openvpn`, `tuntap` and `tunnelblick` installed. Any idea why I'm still having this issue?

**Comment by rodrigogs** [comment]
`Response code 403 (Forbidden)`

Probably your network cant access the API URL: http://www.vpngate.net/api/iphone/

A simple test in your browser will tell us if this is the case. Anyway, I need to catch this error. Thanks!

**Comment by arjunmayilvaganan** [comment]
@rodrigogs Sorry about the delay in response.
Yes, the above mentioned URL was not accessible through my network. Well, my first reason for going with a VPN itself is that certain URL's are blocked in my network. Seems like http://www.vpngate.net/api/iphone/ is also blocked.

Thanks for responding.

**Comment by rodrigogs** [comment]
Maybe I should add a proxy option. What do you think?

**Comment by arjunmayilvaganan** [comment]
Yes, please add that to your to-do, if that's not too much of a work to spend your time on.
