### ISSUE TITLE
Can't get the example working in Ubuntu 16.04

### ISSUE THREAD

**Issue by supirman** [rodrigogs/easyvpn#7]
when I try `openvpn --mktun --dev tun` it give : 
``` 
info: Querying data...
error:  TypeError: May not write null values to stream
    at validChunk (_stream_writable.js:209:10)
    at WriteStream.Writable.write (_stream_writable.js:243:12)
    at resolve (/usr/lib/node_modules/easyvpn/index.js:45:48)
    at Promise._execute (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/usr/lib/node_modules/easyvpn/node_modules/bluebird/js/release/promise.js:77:14)
    at vpns.slice.map (/usr/lib/node_modules/easyvpn/index.js:45:18)
    at Array.map (native)
    at WriteStream.writer.on (/usr/lib/node_modules/easyvpn/index.js:44:41)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:1942:10)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

When I try add country to the command `easyvpn -c US`:
```
info: Querying data...
info: Starting openvpn...
info: Options error: You must define TUN/TAP device (--dev)
info: Use --help for more information.
info:  
info: child process exited with code 1
```

When I look at `/tmp/openvpnconf`, it is empty.

**Comment by rodrigogs** [comment]
I'll have a look at the first error, but I think your network is blocking vpngate.net. The second one is due to the lack of a TUN/TAP adapter... you must have it to work with openvpn.

**Comment by supirman** [comment]
I can access `http://www.vpngate.net/api/iphone/` via browser.

For the 2nd problem I manage to start openvpn with add some argument to the command.
```const proc = spawn(openvpn, ['--dev','tun0', '--config', `"${filePath}"`], { shell: true });```

**Comment by rodrigogs** [comment]
I'll change easyvpn to accept openvpn options as soon as I can.

**Comment by rodrigogs** [comment]
Problems solved:

https://github.com/rodrigogs/easyvpn/releases/tag/v1.2.0
